services:
  postgres:
    image: postgres:18.4
    container_name: db-postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: